export const FEATURED_EVENTS = [
  {
    id: 'evt-symphony-2026',
    venueId: '00000000-0000-0000-0000-000000000001',
    title: 'Grand Symphony Concert',
    title_ar: 'حفل السيمفونية الكبرى',
    category: 'Classical',
    category_ar: 'كلاسيكي',
    date: 'Saturday, Nov 14, 2026 • 8:00 PM',
    date_ar: 'السبت، ١٤ نوفمبر ٢٠٢٦ • ٨:٠٠ م',
    venue: 'Grand Symphony Hall • Auditorium',
    venue_ar: 'قاعة السيمفونية الكبرى • المسرح الرئيسي',
    priceRange: '$45 – $150',
    priceRange_ar: '٤٥$ – ١٥٠$',
    statusPill: 'Live Interactive Map',
    statusPill_ar: 'خريطة تفاعلية حية',
    capacity: '520 Seats',
    capacity_ar: '٥٢٠ مقعداً',
    isPrimary: true,
    description: 'Experience Beethoven’s Symphony No. 9 performed by the Philharmonic Orchestra in our flagship acoustic auditorium with 520 interactive seats.',
    description_ar: 'استمتع بالسيمفونية التاسعة لبيتهوفن بأداء الأوركسترا الفيلهارمونية في مسرحنا الصوتي الرائد المجهز بـ ٥٢٠ مقعداً تفاعلياً.',
    highlights: ['Interactive 520-Seat Topology', 'Orchestra & VIP Tiers', 'Acoustic Soundstage'],
    highlights_ar: ['خريطة تفاعلية لـ ٥٢٠ مقعداً', 'فئات أوركسترا وكبار الشخصيات', 'تصميم صوتي متقدم'],
    imageGradient: 'linear-gradient(135deg, #1E1B4B 0%, #312E81 50%, #4338CA 100%)',
    ctaText: 'Select Seats →',
    ctaText_ar: 'اختر المقاعد ←',
  },
  {
    id: 'evt-cyberpunk-2026',
    venueId: '00000000-0000-0000-0000-000000000001',
    title: 'Cyberpunk Night 2026: Neon Pulse',
    title_ar: 'ليلة السايبربانك ٢٠٢٦: نبض النيون',
    category: 'Rock & Pop',
    category_ar: 'روك وبوب',
    date: 'Friday, Dec 4, 2026 • 9:30 PM',
    date_ar: 'الجمعة، ٤ ديسمبر ٢٠٢٦ • ٩:٣٠ م',
    venue: 'The Industrial Warehouse • Stage A',
    venue_ar: 'المستودع الصناعي • المسرح أ',
    priceRange: '$65 – $180',
    priceRange_ar: '٦٥$ – ١٨٠$',
    statusPill: 'Filling Fast',
    statusPill_ar: 'يوشك على النفاد',
    capacity: '480 Seats',
    capacity_ar: '٤٨٠ مقعداً',
    isPrimary: false,
    description: 'Immersive synthwave, laser installations, and electronic beats featuring international DJ headliners and multi-sensory visuals.',
    description_ar: 'موسيقى سينثويف غامرة، وعروض ليزر وإيقاعات إلكترونية بمشاركة نخبة منسقي الموسيقى العالميين ومؤثرات بصرية مبهرة.',
    highlights: ['Holographic Stage', 'Bass Synthesizers', 'VIP Lounge Access'],
    highlights_ar: ['مسرح هولوغرامي', 'أنظمة باس صوتية فائقة', 'دخول صالة كبار الشخصيات'],
    imageGradient: 'linear-gradient(135deg, #4A044E 0%, #701A75 50%, #A21CAF 100%)',
    ctaText: 'Select Seats →',
    ctaText_ar: 'اختر المقاعد ←',
  },
  {
    id: 'evt-swan-lake-2026',
    venueId: '00000000-0000-0000-0000-000000000001',
    title: 'Swan Lake: Tchaikovsky Masterpiece',
    title_ar: 'بحيرة البجع: رائعة تشايكوفسكي',
    category: 'Theatre',
    category_ar: 'مسرح',
    date: 'Sunday, Dec 20, 2026 • 6:00 PM',
    date_ar: 'الأحد، ٢٠ ديسمبر ٢٠٢٦ • ٦:٠٠ م',
    venue: 'Metropolitan Opera House • Main Hall',
    venue_ar: 'دار الأوبرا المتروبوليتان • القاعة الكبرى',
    priceRange: '$55 – $160',
    priceRange_ar: '٥٥$ – ١٦٠$',
    statusPill: 'Popular',
    statusPill_ar: 'شائع',
    capacity: '500 Seats',
    capacity_ar: '٥٠٠ مقعداً',
    isPrimary: false,
    description: 'The legendary Royal Ballet returns with breathtaking choreography, grand romantic costumes, and live orchestra accompaniment.',
    description_ar: 'يعود الباليه الملكي الأسطوري بتصميم رقصات خلاب وأزياء رومانسية فاخرة بمرافقة أوركسترا حية كاملة.',
    highlights: ['Full Live Orchestra', 'Classical Choreography', 'Royal Box Seating'],
    highlights_ar: ['أوركسترا حية كاملة', 'تصميم رقصات كلاسيكي', 'مقاعد المقصورة الملكية'],
    imageGradient: 'linear-gradient(135deg, #0F172A 0%, #1E293B 50%, #334155 100%)',
    ctaText: 'Select Seats →',
    ctaText_ar: 'اختر المقاعد ←',
  },
  {
    id: 'evt-aurora-2027',
    venueId: '00000000-0000-0000-0000-000000000001',
    title: 'Aurora Solstice Music Festival',
    title_ar: 'مهرجان شمس منتصف الليل للموسيقى',
    category: 'Festivals',
    category_ar: 'مهرجانات',
    date: 'Sat–Sun, Jun 20–21, 2027',
    date_ar: 'السبت–الأحد، ٢٠–٢١ يونيو ٢٠٢٧',
    venue: 'Green Valley Arena • Open Amphitheatre',
    venue_ar: 'حلبة الوادي الأخضر • المدرج المفتوح',
    priceRange: '$89 – $250',
    priceRange_ar: '٨٩$ – ٢٥٠$',
    statusPill: 'Early Bird',
    statusPill_ar: 'الحجز المبكر',
    capacity: '1,200 Seats',
    capacity_ar: '١,٢٠٠ مقعداً',
    isPrimary: false,
    description: 'Two days of non-stop indie, alternative, and electronic acts under the midnight solstice sun with food truck villages and artisan markets.',
    description_ar: 'يومان متواصلان من الموسيقى البديلة والإلكترونية تحت شمس منتصف الليل مع ساحات لعربات الطعام وأسواق الحرف اليدوية.',
    highlights: ['Multi-Stage Access', 'Outdoor Open Arena', 'Campground Add-On'],
    highlights_ar: ['دخول مسارح متعددة', 'مدرج خارجي في الهواء الطلق', 'إمكانية إضافة موقع تخييم'],
    imageGradient: 'linear-gradient(135deg, #064E3B 0%, #065F46 50%, #047857 100%)',
    ctaText: 'Select Seats →',
    ctaText_ar: 'اختر المقاعد ←',
  },
  {
    id: 'evt-electric-horizon-2026',
    venueId: '00000000-0000-0000-0000-000000000001',
    title: 'Electric Horizon Rock Odyssey',
    title_ar: 'ملحمة روك الأفق الكهربائي',
    category: 'Rock & Pop',
    category_ar: 'روك وبوب',
    date: 'Thursday, Jan 15, 2027 • 7:30 PM',
    date_ar: 'الخميس، ١٥ يناير ٢٠٢٧ • ٧:٣٠ م',
    venue: 'Starlight Stadium • Main Stage',
    venue_ar: 'استاد ضوء النجوم • المسرح الرئيسي',
    priceRange: '$50 – $135',
    priceRange_ar: '٥٠$ – ١٣٥$',
    statusPill: 'Selling Rapidly',
    statusPill_ar: 'مبيعات سريعة',
    capacity: '650 Seats',
    capacity_ar: '٦٥٠ مقعداً',
    isPrimary: false,
    description: 'Legendary arena rock tour featuring dual lead guitars, pyrotechnics, and anthemic stadium sing-alongs from three decades of rock history.',
    description_ar: 'جولة روك أسطورية تضم عزف جيتار مزدوج وعروض نارية وأغاني حماسية تاريخية ترددها الجماهير.',
    highlights: ['Pyrotechnic Stage', 'General Admission Pit', 'Collector Tour Pass'],
    highlights_ar: ['مسرح عروض نارية', 'منطقة وقوف حرة', 'بطاقة جولة تذكارية'],
    imageGradient: 'linear-gradient(135deg, #7C2D12 0%, #9A3412 50%, #C2410C 100%)',
    ctaText: 'Select Seats →',
    ctaText_ar: 'اختر المقاعد ←',
  },
  {
    id: 'evt-midsummer-2026',
    venueId: '00000000-0000-0000-0000-000000000001',
    title: "A Midsummer Night's Dream",
    title_ar: 'حلم ليلة منتصف الصيف',
    category: 'Theatre',
    category_ar: 'مسرح',
    date: 'Wednesday, Feb 10, 2027 • 7:00 PM',
    date_ar: 'الأربعاء، ١٠ فبراير ٢٠٢٧ • ٧:٠٠ م',
    venue: 'Globe Arts Pavilion • Center Stage',
    venue_ar: 'جناح فنون غلوب • المسرح الأوسط',
    priceRange: '$40 – $110',
    priceRange_ar: '٤٠$ – ١١٠$',
    statusPill: 'Limited Run',
    statusPill_ar: 'عرض محدود',
    capacity: '420 Seats',
    capacity_ar: '٤٢٠ مقعداً',
    isPrimary: false,
    description: 'Shakespearean magic and comedic brilliance reimagined with contemporary lighting, original musical scoring, and enchanting stagecraft.',
    description_ar: 'سحر شكسبير وكوميديته الرائعة بإخراج معاصر وإضاءة ساحرة وموسيقى تصويرية أصلية تأسر الألباب.',
    highlights: ['Intimate Thrust Stage', 'Original Music Score', 'Cast Talkback Q&A'],
    highlights_ar: ['مسرح تفاعلي مقرب', 'موسيقى تصويرية حصرية', 'جلسة نقاش مع طاقم العمل'],
    imageGradient: 'linear-gradient(135deg, #134E4A 0%, #115E59 50%, #0F766E 100%)',
    ctaText: 'Select Seats →',
    ctaText_ar: 'اختر المقاعد ←',
  },
];
